### ISSUE TITLE
Audio getting Lost - [Long Audio]

### ISSUE THREAD

**Issue by mayankpathak4513** [modelscope/ClearerVoice-Studio#122]
I've observed a bug, when i send an audio file greater than 10 seconds to process the last part of the audio is getting lost/trimmed. I'm not getting the exact audio in output as I passed in the input.

**Comment by JohnPaul-404** [comment]
is it still replicating bro?

**Comment by alibabasglab** [comment]
may I know if you are trying MossFormerGAN_SE_16K? The bug has just been just fixed by a pull request. Thanks.

**Comment by Contraw** [comment]
Ya there is a problem when using the 16khz speech enhancement, will the python package be updated - I still get the issue even when building from source?

**Comment by mayankpathak4513** [comment]
Yes I was using MossFormerGAN_SE_16K and the last part of the speech was getting trimmed, but when i switched to FRCRN_SE_16K model it did worked perfectly.

If bug in MossFormerGAN_SE_16K is fixed, I can give a try with this also, but I've seen a very low latency in FRCRN_SE_16K compared to MossFormerGAN_SE_16K, so I will go ahead FRCRN_SE_16K in my usecase.

Thanks,
